### ISSUE TITLE
EMFILE Error when too many file descriptors/sockets are opened

### ISSUE THREAD

**Issue by bkcompton** [ghdna/athena-express#12]
I ran into an issue in AWS Lambda where my code opened more than the default number of sockets. It resulted in my lambda failing and the following error in CloudFormation.

```
NetworkingError: getaddrinfo EMFILE bucket_name.s3.amazonaws.com:443
```

I resolved it by creating an https.Agent configuring the 'maxSockets' parameter to 5000.
To allow this agent to be used by both Athena and S3 client logic I had to extend the AthenaExpress constructor to allow for an additional awsParams object. The constructor in my PR branch now passes the optional awsParams to both the S3 and Athena constructors.

I believe this flexibility will help alleviate other issues in the future.

See this [commit](https://github.com/bkcompton/athena-express/commit/840a41a3a6dc72369199fa45bf6c9bc6d9ff376d) for resolution

Example of creating additional awsParams object with the https.Agent configured with 5000 maxSockets...

``` 
    const awsOptions = { 
       httpOptions: { 
         agent: new https.Agent({ 
           maxSockets: 5000 
         }) 
       } 
    };  
```
    
Usage: 
```
    const athenaExpressConfig = { 
        awsOptions,  
        aws: awsSdk,  
        db: dbName.toLowerCase(),  
        region,  
        workGroup: athenaWorkgroup,  
        s3: s3SQLLogOutputPath . 
    };
    const athenaExpress = new AthenaExpress(athenaExpressConfig);  
```

**Comment by ghdna** [comment]
You should be able to configure this in the [aws object itself](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-maxsockets.html) before passing that into athenaExpressConfig as below:
```javascript
var AWS = require('aws-sdk');
var https = require('https');
var agent = new https.Agent({
   maxSockets: 25
});

AWS.config.update({
   httpOptions:{
      agent: agent
   }
});
```
That way you can simply pass aws object into athena-express without changing anything on athena-express.

**Comment by bkcompton** [comment]
Greg, 
Thank you for pointing this out!
I should have known that this low level configuration could be done at this more general location.
I agree that awsOptions can/should be configured at the AWS.config level.

However, the athenaWorkgroup is still needed in the athena-express configuration parameter IMHO.

I am new to contributing to open source projects so please let me know if you would like me to clean up and remove awsOptions from config within this PR branch or if you will be implementing it directly in another feature branch.

Thank you for your work!

**Comment by ghdna** [comment]
no worries, we are all learning. Let me educate myself about workgroups as it seems to be a relatively new concept and I haven't used it yet.

**Comment by ghdna** [comment]
Sorry this took a long. But the workgroup issue is fixed in the latest push courtesy of @aspirewit
