### ISSUE TITLE
Skip Fetch Result

### ISSUE THREAD

**Issue by phasath** [ghdna/athena-express#14]
There should be an option to skip fetch results. I have many cases where I want Athena to process something, save it to S3, return only the QueryExecutionID, and then, download it separately as a csv. 

Currently, as far as I know, there is no way to do this.

**Comment by ghdna** [comment]
So basically download csv at a later time outside of athena-express? 
There is a way to achieve this. set `getStats` as `true` in the `athenaExpressConfig` and execute your query. This will return the QueryExecutionID that you can capture and use later. Just ignore the results.

**Comment by phasath** [comment]
I know that I can just ignore, but it will take a while to fetch all my S3 results, and I can't spend workload on this. A flag to skip that step would be much appreciated.

**Comment by ghdna** [comment]
Executing and waiting for the query to finish in Athena is where you spend the most time & workload. Fetching from S3 is peanuts comparatively. 
Let me think about the applicability of this feature for other use cases. Meanwhile feel free to fork it and skip that step.

**Comment by phasath** [comment]
The applicability would be, for example, processing something on backend and just sending the s3 public link to frontend download.

**Comment by ghdna** [comment]
hmm, okay I'll add it.
