### ISSUE TITLE
Lambda deployment - error with csvtojson

### ISSUE THREAD

**Issue by jamesp26** [ghdna/athena-express#16]
Don't know if this is the best place to ask. I've been using athena-express in Lambda deployments for a while. Projects are created in VSCode using the SAM toolkit addin.

Upgrading to the latest athena-express gives me the following error when running a deployment:

_the system cannot find the path specified: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\aws-toolkit-vscode\\samDeployjOq0gP\\build\\xxx\\node_modules\\csvtojson\\.ts-node\\4c960549db1acf61706147e6827e627a7fda2f32ddc1336b4438c12d731ddee1\\09978396b133849a0d0f83c9c100b167a1060208a0fdf57d39dc695ae209e0c9.js_

All other libraries i've been using work fine. Any ideas?

**Comment by ghdna** [comment]
I'll try to help. With Lambda, you have to package and upload everything, including dependencies. csvtojson is a dependency. So make sure when you zip up athena-express, you also include the nodemodules folder as that contains all dependencies.

**Comment by jamesp26** [comment]
Thanks for replying. I'm aware of all that but the AWS Toolkit takes care of all of that when you do a deployment from a project. For some reason, it has an issue with csv2json in the latest version. Will need to investigate as its probably just with that library.

**Comment by ghdna** [comment]
Ok, let me know how I can help. Do make sure that on Lambda console, you can navigate to the nodemodules and see the csvtojson folder.

**Comment by jamesp26** [comment]
Yes its there. Will try creating a project from scratch that just contains csvtojson .

**Comment by jamesp26** [comment]
So it happens with a test project where i only include csvtojson. If i force the version to 2.0.8 it deploys fine so there is something wrong with the newer version.  Will raise a case on their Git page. Do you know if you used any specific functionality in 2.0.8?

Not this only occurs when going through the deployment process in VSCode when using the AWS Toolkit add-in. Developing locally is fine.

**Comment by ghdna** [comment]
No there is nothing tied to a specific version of csvtojson.

**Comment by jamesp26** [comment]
I had other issues with previous versions of csvtojson. For now i've forked the library to used csv-parse instead which deploys fine for me. Its possible i should be deploying differently anyway so will come back to this at a later date.
