### ISSUE TITLE
Amazon API Gateway times out after 29 seconds

### ISSUE THREAD

**Issue by trevorlazarus** [ghdna/athena-express#18]
When Athena Queries take longer the 29 seconds to execute, the API gateway returns a "Endpoint request timed out" message. 

Has anyone else faced this issue and if so, could you please give me some advice.

**Comment by ghdna** [comment]
Yes, API Gateway has a hard [limitation](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html#api-gateway-limits) of 29 seconds. Here are few ways you can mitigate this:

- Make use of `skipResults: true` in athena-express configuration. This will initiate the query, store the results in S3, and give you a reference to S3. You can then fetch the results from S3 in a subsequent request after waiting a few seconds.
- Ensure that your Athena queries are optimized through `where` and `limit` clause to take less than 29 seconds. 
-  Skip API Gateway and instead invoke Lambda directly

**Comment by trevorlazarus** [comment]
Thanks @ghdna, will try this out. I'm also looking at using WebSockets instead of REST.
