### ISSUE TITLE
Workgroup support

### ISSUE THREAD

**Issue by dchertousov** [ghdna/athena-express#19]
Hi!

We found your wrapper very useful for us and going to use it in production, but there is one feature missing for us.

We need to provide Workgroup for instance of `AthenaExpress` or for the particular query.
Do you plan such functionality in future? If not, would you support such contribution?

Many thanks!

**Comment by ghdna** [comment]
Yes, I thought someone had pushed that in. Let me check. If it's not there, I'll add it in.
