### ISSUE TITLE
Add option to skip waiting for query to complete and manually check status

### ISSUE THREAD

**Issue by ignacioblit** [ghdna/athena-express#22]
Hello! 

With the new addition of INSERT operations to Athena, it makes sense being able to execute queries without waiting for their completion. Having said this it would be nice to have the option to skip waiting for the results in addition to having a new method to check the query status.

I checked the current codebase and implementing this should be fairly straightforward. I'm up for sending a PR if this change is approved.

**Comment by ghdna** [comment]
Sure, send a PR. Update the documentation as well.

**Comment by ignacioblit** [comment]
Thanks for the quick response!

The PR has been opened:
https://github.com/ghdna/athena-express/pull/23

**Comment by ignacioblit** [comment]
Hi! 

Please let me know if you want any changes on the PR or when it could get merged. Thanks!

**Comment by ghdna** [comment]
I'm looking through it. Can you ensure that this PR only contains this single incremental change?

**Comment by ignacioblit** [comment]
I added the possibility to override configuration with an additional parameter on the query method and also added a Linear backoff for the commonAthenaErrros, which felt a little bit better.

**Comment by ignacioblit** [comment]
Any news on this?

**Comment by ghdna** [comment]
Went through the PR. Seems to work. Organizing the code a bit.

**Comment by ghdna** [comment]
This is completed. Thanks for the PR.
