### ISSUE TITLE
Athena Pagination

### ISSUE THREAD

**Issue by howdyhyber** [ghdna/athena-express#24]
Greetings!

Is there a feature is Athena Express for Paginating results. It would be very helpful.

**Comment by ghdna** [comment]
There is a way. If you enable `skipResults` in athena-express configuration, you will not receive the results of your athena query. Instead you will receive an S3 link to the results, which you can fetch on your own as needed, including in paginated chunks. I can look into making this easier.

**Comment by ranguard** [comment]
paginated results in an east way would be fantastic

**Comment by ghdna** [comment]
Ok, I'll look into it

**Comment by tanbyte** [comment]
Hi there- is the pagination feature part of recent release? It’ll be very helpful. Thanks!

**Comment by ghdna** [comment]
This certainly seems to be a high in-demand feature. I'll prioritize this one next. Interestingly, the first version of athena-express had pagination but there were requests to enable streaming from S3 to make the APIs more responsive.

**Comment by ghdna** [comment]
Pagination has been added in the v7 that was pushed today. Available on GH and NPM. `{pagination: 10}` can be added in the query. See Readme for details and examples. Thanks for your patience with this.

**Comment by ranguard** [comment]
Thank you for implementing! :)

**Comment by ghdna** [comment]
Thanks for bringing this to my notice. Closing this now.
