### ISSUE TITLE
'SHOW TABLES' query is timing out

### ISSUE THREAD

**Issue by GuidoS** [ghdna/athena-express#27]
Hello,

I am running into timing out issues with my queries, even the "SHOW TABLE" query is timing out and I know that one should always run within ~30ms.

Here is the function I am using:
```js
'use strict'
const AWS = require('aws-sdk')
const AthenaExpress = require('athena-express')

const getData = async (event) => {
    if (!event.query) {
        event.query = 'SHOW TABLES'
    }

    const athenaExpressConfig = {
        aws: AWS
    }

    const athenaExpress = new AthenaExpress(athenaExpressConfig)
    event.data = await athenaExpress.query({
        sql: event.query
    })

    return event
}
```

Any suggestions on how I can get this to work would be appreciated.

**Comment by ghdna** [comment]
`Show Tables` shouldnt take long unless you have other issues related to network,. Can you check on Athena console how long these queries are taking?

**Comment by GuidoS** [comment]
Turns out this issue was one related to vpc settings that I added and I didn't realize that this was going to cause an issue.
