### ISSUE TITLE
Add QueryQueueTimeInMillis, QueryPlanningTimeInMillis & TotalExecutionTimeInMillis in stats

### ISSUE THREAD

**Issue by rakekris** [ghdna/athena-express#32]
Hi Gary

This is more of an enhancement . we are using Athena express in one of our serverless architecture based project. We would need QueryQueueTimeInMillis, QueryPlanningTimeInMillis & TotalExecutionTimeInMillis in the Athena stats so that we will be able to decide weather query is taking time due to queuing or taking more time execute.

Thanks in advance
rocky

**Comment by ghdna** [comment]
Good idea. Let me push that change in the next version.

**Comment by rakekris** [comment]
thanks @ghdna  !!!

**Comment by ghdna** [comment]
Fixed in latest. Will push to NPM shortly.

**Comment by rakekris** [comment]
@ghdna  thanks a ton!
