### ISSUE TITLE
Athena is not a constructor

### ISSUE THREAD

**Issue by sonupsp3** [ghdna/athena-express#36]
Hi,

Getting Athena is not a construction error while using browserify. It looks like Athena is not included in the brower sdk. Could you please suggest how to resolve this issue?

**Comment by ghdna** [comment]
are you able to use it in a regular node.js application like the example in readme?

**Comment by sonupsp3** [comment]
Yes this works fine in a regular node.js application

**Comment by ghdna** [comment]
Thats the primary usage of this package: As a standalone nodejs app or a lambda function. I haven't tested it outside of these two. if you know what is missing, feel free to submit a PR.

**Comment by sonupsp3** [comment]
Sure,  I'm still investigating.  I'll submit a PR once I found the solution.
Thanks
