### ISSUE TITLE
Allow setting ClientRequestToken when starting an query execution

### ISSUE THREAD

**Issue by jrbarnard** [ghdna/athena-express#37]
If the service running the query times out before the query finishes running / gets off the queue, if it retries it will re start the query.
Ideally we'd be able to set the [ClientRequestToken](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Athena.html#startQueryExecution-property) through athena express to make an idempotent request.

Suggested syntax:
```
await athenaExpress.query({
    sql: '...',
    clientRequestToken: '...'
});
```

I'm happy to PR this, cheers

**Comment by ghdna** [comment]
Not sure if this is a valid scenario as athena-express waits until the query is finished executing and it does so by checking every 200 milliseconds (default value) on the query status. Furthermore, if you don't care about fetching the results immediately, you can set `skipResults: true` and use the returned values of `QueryExecutionId` & `S3Location` to fetch results later on demand

**Comment by jrbarnard** [comment]
The use case would be if your request times out before it's exited the
Athena express query method. If you then retry the request it will start a
new query rather than pick up where it left off.

Athena's max query time is 30 minutes by default and depending on the time
of day multiple minute queue / query times are realistic.

**Comment by ghdna** [comment]
oh ok. Let me look into it.

**Comment by ghdna** [comment]
This can now be achieved by setting `waitForResults: false` in the athena-express configuration. This will return a `QueryExecutionId` as soon as the query begins. You can then pass `QueryExecutionId` back into athena-express some time later.
