### ISSUE TITLE
Always rertuns response with string in json key:value

### ISSUE THREAD

**Issue by mayank-kanzariya** [ghdna/athena-express#38]
Always rertuns response always with string in json key:value instead of proper relavant data type in athena table definition

For example:
In athena table definition:
```
device_mac string,
timestamp bigint,
device_action boolean
```
but athena-express return response with string only
```
{
      device_mac: 'A7:A8:3D:16:F3:35',
      timestamp: '1587829688',
      device_action: 'true'
}
```
expected result:
```
{
      device_mac: 'A7:A8:3D:16:F3:35',
      timestamp: 1587829688,
      device_action: true
}
```

**Comment by ghdna** [comment]
Amazon Athena stores result in that format in S3, which is where athena-express picks it from. Data type is not stored within the results to know which values are strings vs integers.

**Comment by mayank-kanzariya** [comment]
Thanks Gary for quick response,
 
I aggreed to you, but one of the my concern is , while executing athena query using 'aws-sdk', it will give us data with data type and column name. Hence, we can easily find out data type of a given columns. 

Actuallay, in some case number may also stored as a string, hence , it's difficult to identify the data type of a column. However, I don't want to put hard code logic for type conversion in backend application like, 'device_mac'  always convert as a string, and if I want to add another column, then I also need to update the backend application, that I don't want.

Please help me to resolve this concern.

Thanks in advance!

**Comment by ghdna** [comment]
This package also uses aws-sdk to execute the queries. Which method you are using to see the data type and column name?

**Comment by mayank-kanzariya** [comment]
In 'aws-sdk' , the 'getQueryResults' in Athena method returns the data type and column name.

Here, partial code snippet for refference

```
const AWS = require("aws-sdk");
const athenaClient = new AWS.Athena({});
const results = await athenaClient.getQueryResults({ QueryExecutionId }).promise();
```

**Comment by ghdna** [comment]
This package also uses `getQueryResults` to fetch results from Athena. The contents of results depend on the query you executed in `startQueryExecution` . which query are you executing?

**Comment by mayank-kanzariya** [comment]
I am executing below query using 'startQueryExecution' method 

**Query:** `select device_mac,x,y,z,device_temperature,device_humidity,device_action from <TABLE NAME> where device_mac = '<DEVICE MAC>' AND timestamp BETWEEN 1585220682 AND 1585650514  AND year BETWEEN '2020' AND '2020'   AND month BETWEEN '3' AND '3'   AND day BETWEEN '26' AND '31'  order by timestamp`

**Comment by ghdna** [comment]
Try one thing: set `formatJson: false` in the athena-express configuration. After I fetch results from `getQueryResults`, I clean up to make the JSON readable. To read the raw results from S3, try doing this and tell me what you see.

**Comment by mayank-kanzariya** [comment]
I have set `formatJson: false` in the athena-express configuration as below. But still, I am getting response in string as below.
`{
  Items: [
    '"device_mac","timestamp","device_action"',
    '"A7:A8:3D:16:F3:35","1587475090","true"',
    '"A7:A8:3D:16:F3:35","1587475091","true"',
    '"A7:A8:3D:16:F3:35","1587475092","true"',
    '"A7:A8:3D:16:F3:35","1587475093","true"',
    '"A7:A8:3D:16:F3:35","1587475134","true"',
    '"A7:A8:3D:16:F3:35","1587475135","true"',
  ]
}`

**Comment by ghdna** [comment]
oh okay. I see what is going on. Give me a few days to address this.

**Comment by mayank-kanzariya** [comment]
Hi Gary, 
Thanks for the update and attention on this issue.

**Comment by ghdna** [comment]
I published a new version of athena-express on npm. Try that and let me know.

**Comment by mayank-kanzariya** [comment]
Hi Gary,

Thanks a lot and appriciate you kind consideration and quick response in this issue.

Now, I am able to receive the JSON with proper data type value.

`    {
      device_mac: 'A7:A8:3D:16:F3:35',
      timestamp: 1587475229,
      device_action: true
    }`

**Comment by ghdna** [comment]
Awesome. Thanks for bringing this to my notice. Closing this now.
