### ISSUE TITLE
You Need to Update the NPM Package

### ISSUE THREAD

**Issue by jeff-predictwise** [ghdna/athena-express#45]
Latest version 6.0.3 does not include the fixes to the typescript typings file.

**Comment by hi019** [comment]
*Please ;)

For now you can just do the following to install this:

npm: `npm install git://github.com/ghdna/athena-express/` (haven't tried)

yarn: `yarn add https://github.com/ghdna/athena-express/`

**Comment by ghdna** [comment]
Done

**Comment by jeff-predictwise** [comment]
Thank you maintainers!
