### ISSUE TITLE
Extremely High Number of Get Requests

### ISSUE THREAD

**Issue by igorescobar** [ghdna/athena-express#47]
Hi,

I have a lambda function that every day, goes over ~100 records and triggers a query about each one of those records.  These are the number of requests send to S3 every time this lambda triggers:

<img width="1104" alt="Screenshot 2020-10-28 at 21 25 16" src="https://user-images.githubusercontent.com/24032/97498467-28640680-1964-11eb-9c19-29d6c96aa34f.png">

In the beginning, I thought that it was the default `retry`... changed it to 5000 and got the same result.

Any ideas why would something like this happen?

**Comment by igorescobar** [comment]
FYI: I only noticed this because I was receiving some lambda failures with S3 complaining that I was doing too many requests per second.

**Comment by ghdna** [comment]
Need more context. AthenaExpress fires off a request to Athena every 200 milliseconds to check if the query has finished processing. This is a light payload query. Once the query has finished processing, then AthenaExpress fetches the result from S3 via a process stream.
