### ISSUE TITLE
Internet requirement 

### ISSUE THREAD

**Issue by taranjitGH** [ghdna/athena-express#55]
Hi,

I was unable to get results while executing " athenaExpress.query(sqlQuery)" from within a private subnet (without having internet access) of AWS Lambda function. It seems internet accessibility is required for successful invocation. Correct ? As I was able to get the results when I enabled internet for that Lambda function.

If so, why internet is required to invoke athenaExpress.query(sqlQuery) ?

Regards,
Taranjit

**Comment by ghdna** [comment]
thats because S3 requires internet connectivity (unless you use VPC endpoint)
