### ISSUE TITLE
Instantiate with credentials

### ISSUE THREAD

**Issue by cro13** [ghdna/athena-express#57]
The library should allow passing in of IAM credentials, similar to the way AWS services in the SDK are doing it.
At the moment the credentials have to be set globally, which makes it impractical if you are doing cross-accounts athena access.

**Comment by ghdna** [comment]
There are two options around this requirement:
1. Explicit: Instantiate an AWS SDK object by passing in the access key/secret key as shown [here](https://github.com/ghdna/athena-express#configuration)
2. Implicit: Run athena-express from any AWS host (e.g. Lambda or EC2) that already has the appropriate IAM role attached to it.
