### ISSUE TITLE
Querying Athena using athena-express

### ISSUE THREAD

**Issue by pabrahamusa** [ghdna/athena-express#58]
I am new to javascript and Athena . However trying to use athena-express with a nodejs Lambda to execute Athena Query. I am trying to enable `waitForResults` and get the QueryExecutionId so that I can fetch the results afterwards.  I tried following code but not working..!  it seems stuck at `result = await p1;` . As per the documentation it should return the QueryExecutionId without any latency. Appreciate any help here. 

```
const AE = require("athena-express");
var aws = require("aws-sdk");

async function getAthenaData(query) {
  console.log(" query == " + query);

  const athenaExpressConfig = {
     aws,
     s3: "s3://sb-mydata-nonprod-logs/results",
     getStats: true,
     workgroup: "primary",
     retry: 1000,
     waitForResults: false
  };

 const athenaExpress = new AE(athenaExpressConfig);
 let p1 = athenaExpress.query(query);

 let result = "empty Query Execution ID";
 console.log(" Start resolve Promise");
 result = await p1;
 console.log(" Results after Promise === " + result);
 console.log(" End resolve Promise");
}
```

**Comment by ghdna** [comment]
the code is not structured right. Move the initializing of athena-express outside async and only execute the query within async. Follow [this](https://github.com/ghdna/athena-express#using-aws-lambda) closely
