### ISSUE TITLE
Use metadata to generate object JS

### ISSUE THREAD

**Issue by wzomer** [ghdna/athena-express#6]
Currently the response columns always is String, maybe we can use the metadata file (.csv.metadata) to generate the object js better, what do you think?

**Comment by ghdna** [comment]
Good idea. Though it could have a slight performance hit as the results are streamed from S3 and will need datatype check for each set of rows (so lots of conditional checkpoints). But if you wanna take a stab at developing it, I'll be happy to include it as an add-on configuration.
