### ISSUE TITLE
Feature request: tag releases in GitHub

### ISSUE THREAD

**Issue by neverendingqs** [ghdna/athena-express#61]
By tagging the releases, users can use the tags to discover what was introduced between releases.

If desired, here's an example of how to create a release all via GitHub Actions (including tagging the release) (sadly, does not work with branch protection today): https://github.com/neverendingqs/serverless-dotenv-plugin/blob/master/.github/workflows/release.yml

If that looks like something you're interested in, I'm happy to help out by submitting a pull request.

**Comment by ghdna** [comment]
Last released was tagged. Thanks for bringing it to my notice.
