### ISSUE TITLE
Pagination causing data loss

### ISSUE THREAD

**Issue by devanshumadan** [ghdna/athena-express#65]
Hi,

While using pagination (and NextToken), I noticed some data loss. When I debugged the code, it looks like the 'getQueryResults' method responds with column names only when 'NextToken' is not present in the request.

In line 96, helper.js - we don't need to add + 1 every time.

Could you please look into this issue?

I have made few changes in the file for your reference (please do a diff check). 

To reproduce the issue:
Set limit to '3' in the query, and set page size as '1'. You will notice that we get the first record in the first response (without NextToken), but in the subsequent request (with NextToken), we get the third record, and the second record is getting skipped.

Thank you!

- Devanshu Madan
[helpers.js.zip](https://github.com/ghdna/athena-express/files/6515008/helpers.js.zip)

**Comment by ghdna** [comment]
Valid issue. Looking into it.

**Comment by devanshumadan** [comment]
@ghdna Gary, I tested the changes in the file which I attached. Seems to be working fine.
The solution is not very clean though.

**Comment by ghdna** [comment]
Your solution was pretty solid. I updated it slightly and incorporated in v7.1.0. Do test it out and let me know if I can close this. Good catch on this issue!

**Comment by devanshumadan** [comment]
Thank you @ghdna. I tested the updated version. The bug is fixed.
Closing the issue.
