### ISSUE TITLE
Unable to get S3 location for result

### ISSUE THREAD

**Issue by ghoastfalcon** [ghdna/athena-express#71]
Hi,

First off, thank you for creating this library, it has made my job a lot easier :). I was wondering if there is support to pull the result S3 location out of the library. I am not finding an option to enable in the settings. But I did see where the functionality could be added. My use case is that I need to update a dynamo record with the result URL for a query so that we can track the queries being run in Athena via API calls, which leverage this library.

I wanted to see if this was something on your roadmap and if need be I could put a PR in with the update. 

Thank you for your time,

-Barrett-

**Comment by ghoastfalcon** [comment]
Nevermind, I found it. Thanks!

**Comment by ghdna** [comment]
Glad it worked. For anyone else wondering, you can use skipResults or waitForResults. Check out the documentation for more info.
