### ISSUE TITLE
Datatype 'bigint' is not handled

### ISSUE THREAD

**Issue by AndreasNeuwirth** [ghdna/athena-express#79]
When the result of a query is converted to Json, columns with datatype `bigint` are converted to a string instead of to a number because the specific case is missing (https://github.com/ghdna/athena-express/blob/master/lib/helpers.js#L224).

**Comment by ghdna** [comment]
Updated. Do note that now bigint will be denoted by a trailing `n` as per the [MDN definition of big int](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)

**Comment by AndreasNeuwirth** [comment]
Sorry, it seams I was a bit unclear, I expected it to be cast to a Number like the other int variants.

**Comment by ghdna** [comment]
That's why I had left it as string. But now Athena-express correctly represents it as type Bigint. The trailing 'n' can seem awkward but its the accurate denotation of bigint.
