### ISSUE TITLE
Clean up the s3 file after the query

### ISSUE THREAD

**Issue by chuenlok** [ghdna/athena-express#8]
With the library, I can't find a way to clean up the file generated by the query. I wonder if there is a way to get path of the files(xxx.csv and xxx.csv.metadata) generated so that I can do house keeping in the folder?

**Comment by ghdna** [comment]
You could create a [S3 Lifecycle Policy](https://docs.aws.amazon.com/AmazonS3/latest/user-guide/create-lifecycle.html) to automatically delete (expire) objects in your bucket after a specific interval (e.g. 30 days). 
To know where those files are stored in S3, you could either provide your own S3 bucket name in `athenaExpressConfig` [object](https://github.com/ghdna/athena-express#option-2-advance-configuration) or let athena-express create one for you (e.g. athena-express-XXXXXX).

**Comment by ghdna** [comment]
Update: If you really need to know the specific S3 file used to an execution, just enable `getStats: true` in the `athenaExpressConfig` constructor and you will get the S3Location in the response.
