### ISSUE TITLE
BIGINT type data returning as string

### ISSUE THREAD

**Issue by ncoughlin** [ghdna/athena-express#84]
I'm having an issue where all of my data that is in the BIGINT format is being returned as a string instead of a number.
There are workarounds on the receiving end but it would be much better if it was returning straight number format.

**Comment by ghdna** [comment]
See #79 
The trailing 'n' and the string datatype can seem odd but its actually the accurate denotation of [bigint primitive](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)
