### ISSUE TITLE
parameter types of athena express query function don't seem to match documentation

### ISSUE THREAD

**Issue by mtin79** [ghdna/athena-express#88]
hi there,
trying to use your example of a query config object as a parameter in the query function throws typescript errors!
<img width="2118" alt="Screenshot 2022-09-14 at 10 37 50" src="https://user-images.githubusercontent.com/46390/190105012-cda722c3-baf3-46ef-9f78-913dfda84cef.png">

Should i just ignore the typescript errors? 

Also the documentation says that pagination format should be a string but examples are with numbers.
<img width="871" alt="Screenshot 2022-09-14 at 10 38 52" src="https://user-images.githubusercontent.com/46390/190105229-2090d089-3179-4fc7-b1ef-44a7214019de.png">

Thanks for help!!!

**Comment by romanlamsal** [comment]
the other advanced query parameters are also missing. Until the PRs are merged for that, you can create an `augment.d.ts` file in your project and paste the following content

```ts
declare module "athena-express" {
    interface QueryObjectInterface {
        db?: string
        pagination?: number
        NextToken?: string
        QueryExecutionId?: string
        catalog?: string
    }
}

export default {}
```

make sure to include the last line, otherwise you will not augment but override the typings.
