### ISSUE TITLE
Return QueryExecutionId in query method

### ISSUE THREAD

**Issue by jamesp26** [ghdna/athena-express#9]
Would be really useful if you added results.QueryExecutionId = queryExecutionId; to the query method. We are building a separate process to cache frequently run queries and want to use the executionId as the identifier. Is that possible?

**Comment by ghdna** [comment]
Yes, good suggestion. I've updated the package with this feature in v5.0.4. Just set `getStats: true` in the `athenaExpressConfig` constructor and you will get the QueryExecutionId in the response.
